
CREATE TABLE EMPLOYEE (
  ID  BIGINT AUTO_INCREMENT,
  FIRST_NAME VARCHAR (200)  NOT NULL ,
  LAST_NAME VARCHAR (200)  NOT NULL
);

CREATE TABLE USER (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR (95)  NOT NULL ,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  INSTANCE_NAME VARCHAR (200)  NOT NULL ,
  FIRED_TIME BIGINT NOT NULL ,
  SCHED_TIME BIGINT NOT NULL ,
  PRIORITY INTEGER NOT NULL ,
  STATE VARCHAR (16)  NOT NULL,
  JOB_NAME VARCHAR (200)  NULL ,
  JOB_GROUP VARCHAR (200)  NULL ,
  IS_NONCONCURRENT BOOLEAN  NULL ,
  REQUESTS_RECOVERY BOOLEAN  NULL 
);

ALTER TABLE EMPLOYEE  ADD
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY  
  (
    ID
  );

COMMIT;